### PR TITLE
use TF 0.12.9 in pipeline

### PR DESCRIPTION
**Pull request by sh31**
* Update buildspec to use Terraform 0.12.9 instead on 0.12.6

### CODE REVIEW

**Comment by r4vi** [comment]
latest is 12.12 might as well use that?

**Comment by djsd123** [comment]
I'd stay away from the latest.  It's terraform

**Comment by r4vi** [comment]
@djsd123 
@sh31 is the YOLO master

**Comment by djsd123** [comment]
Squash your commits

**Pull request merged**
